// Generated by CoffeeScript 1.3.3

TestCase("Array Test", {
  "test array splice should modified array": function() {
    var arr, result;
    arr = [1, 2, 3, 4, 5];
    result = arr.splice(2, 3);
    assertEquals([1, 2], arr);
  },
  "test array splice should return modified array": function() {
    var arr, result;
    arr = [1, 2, 3, 4, 5];
    result = arr.splice(2, 3);
    return assertEquals([3, 4, 5], result);
  }
});
