// Generated by CoffeeScript 1.3.3

console.log("Hello");

console.log("Hello");

console.log("Hello");

console.log("Hello");

if (true) {
  console.log("Hello");
}

if (true) {
  console.log("こんにちは！");
}
