// Generated by CoffeeScript 1.3.3
(function() {

  alert("Hello");

  alert("Hello");

  alert("Hello");

  alert("Hello");

  if (true) {
    alert("Hello");
  }

  if (true) {
    document.write("こんにちは！");
  }

}).call(this);
