// Generated by CoffeeScript 1.3.3

console.log(100);

console.log(0x10);

console.log(0xff);

console.log(0xc);

console.log(2 + 3);

console.log(5 - 3);

console.log(10 * 20);

console.log(20 / 10);

console.log(7 % 2);
