// Generated by CoffeeScript 1.3.3
var foo, hoge;

hoge = 100;

/* is
*/


console.log(hoge === 100);

console.log(hoge === 200);

/* isnt
*/


console.log(hoge !== 100);

console.log(hoge !== 200);

/* not
*/


hoge = 128;

console.log(!(hoge === 128));

console.log(!(hoge === 100));

/* and
*/


hoge = 64;

foo = 128;

console.log((hoge === 64) && (foo === 128));

console.log((hoge === 64) && (foo === 100));

/* or
*/


hoge = 64;

foo = 128;

console.log((hoge === 64) || (foo === 128));

console.log((hoge === 64) || (foo === 100));

/* true/yes/on
*/


console.log(true === true);

console.log(true === true);

console.log(true === true);

/* false/no/off
*/


console.log(false === false);

console.log(false === false);

console.log(false === false);
