// Generated by CoffeeScript 1.3.3
/* while
*/

var arr, element, i, key, num, obj, value, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _len5, _m, _n, _step;

num = 10;

while (num > 0) {
  console.log(num);
  --num;
}

/* while at the end
*/


num = 10;

while (num++ < 10) {
  console.log(num);
}

/* until
*/


num = 10;

while (!(num < 0)) {
  console.log(num);
  --num;
}

/* while return
*/


num = 0;

arr = (function() {
  var _results;
  _results = [];
  while (num < 5) {
    _results.push(num++ * 2);
  }
  return _results;
})();

console.log(arr);

/* for
*/


arr = [1, 2, 3, 4, 5];

for (_i = 0, _len = arr.length; _i < _len; _i++) {
  i = arr[_i];
  console.log(i);
}

/* for at the end
*/


arr = [1, 2, 3, 4, 5];

for (_j = 0, _len1 = arr.length; _j < _len1; _j++) {
  i = arr[_j];
  console.log(i);
}

/* for - index in loop
*/


arr = ['a', 'b', 'c'];

for (value in arr) {
  key = arr[value];
  console.log("" + key + ", " + value);
}

/* for - use in array
*/


obj = {
  foo: "str",
  bar: 100,
  baz: true
};

for (key in obj) {
  element = obj[key];
  console.log("" + key + ": " + element);
}

/* for - use in array at the end
*/


obj = {
  foo: "str",
  bar: 100,
  baz: true
};

for (key in obj) {
  element = obj[key];
  console.log("" + key + ", " + element);
}

/* for - by - the statement of step
*/


arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

for (_k = 0, _len2 = arr.length; _k < _len2; _k++) {
  value = arr[_k];
  console.log(value);
}

console.log("step by 2");

for (_l = 0, _len3 = arr.length, _step = 2; _l < _len3; _l += _step) {
  value = arr[_l];
  console.log(value);
}

/* for - break
*/


arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

for (_m = 0, _len4 = arr.length; _m < _len4; _m++) {
  value = arr[_m];
  console.log(value);
  if (value === 5) {
    break;
  }
}

/* for - continue
*/


arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

for (_n = 0, _len5 = arr.length; _n < _len5; _n++) {
  value = arr[_n];
  console.log(value);
  if (value === 5) {
    continue;
  }
}
