// Generated by CoffeeScript 1.3.3
/* basic
*/

var pow, pow2, print, sum, sum2, sum3,
  __slice = [].slice;

print = function(str) {
  return console.log(str);
};

print("Hello Coffee Script!");

/* return value
*/


pow = function(n) {
  return n * n;
};

print(pow(5));

/* return value without return
*/


pow2 = function(n) {
  return n * n;
};

print(pow2(15));

/* arguments
*/


sum = function(a, b) {
  return a + b;
};

print(sum(1, 99));

/* arguments with default
*/


sum2 = function(a, b) {
  if (b == null) {
    b = 100;
  }
  return a + b;
};

print(sum2(10, 20));

print(sum2(5));

/* Variable-length argument
*/


sum3 = function() {
  var n, s, t, _i, _len;
  n = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  s = 0;
  for (_i = 0, _len = n.length; _i < _len; _i++) {
    t = n[_i];
    s += t;
  }
  return s;
};

print(sum3(2, 4));

print(sum3(1, 2, 3, 4, 5, 6, 7, 8, 9, 10));

/* Omit the parentheses
*/


print("Hello World!");

print("Hello World!");
