// Generated by CoffeeScript 1.3.3
/* Basic
*/

var i, m, r, str, t, _i, _len;

str = "abcdefgcde";

console.log(str);

str = str.replace(/cde/g, "CDE");

console.log(str);

/* Here RegExp
*/


str = "rgba(128, 64, 255)";

r = /^rgba\((\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\)$/;

m = str.match(r);

for (i = _i = 0, _len = m.length; _i < _len; i = ++_i) {
  t = m[i];
  console.log("" + i + ", " + t);
}
