// Generated by CoffeeScript 1.3.3
var output;

output = function(text, color) {
  var p;
  p = document.createElement("p");
  p.innerHTML = text;
  p.style.color = color;
  return document.body.appendChild(p);
};
