// Generated by CoffeeScript 1.3.3

testCase("String Trim Test", {
  "test should trim remove trailing white-space at start": function() {
    return assert("should trim remove trailing white-space at the start", "a string" === " a string".trim());
  },
  "test should trim remove trailing white-space at end": function() {
    return assert("should trim remove trailing white-space at the end", "a string" === "a string ".trim());
  }
});
