// Generated by CoffeeScript 1.3.3
var num, obj;

obj = {
  hoge: "hoge"
};

num = 100;

/* Javascript standerd stype
*/


console.log("Hello");

/* Not semicolon
*/


console.log("Hello");

/* Not Brakets
*/


console.log("Hello");

/* Not semicolon and brakets
*/


console.log("Hello");

/* Place holder % type
*/


console.info("Hello %s", "coffee script");

console.log("This is %j.", obj);

console.log("%s:%s", "A", "B", "C");

/* Place holder #{} type
*/


console.log;

console.log('#{num}');

console.log("" + num);

if (true) {
  console.log("Hello");
}

if (true) {
  console.log("こんにちは！");
}
