// Generated by CoffeeScript 1.3.3

console.log('abcde');

console.log("あいうえお");

console.log("いつも元気です。これからもがんばります。");

console.log("<code>\n  var str = \"abcde\";\n  console.log(str);\n</code>");

console.log("式展開" + (128 * 128) + "されます！");

console.log('式展開#{128 * 128}されません！');

console.log("Hello," + "World");
