// Generated by CoffeeScript 1.3.3
var app, express, port;

express = require('express');

app = express();

app.get('/', function(req, res) {
  console.log("/ hit!");
  return res.send("Hello World!");
});

port = process.env.PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port);
});
