// Generated by CoffeeScript 1.3.3
var addToArray;

addToArray = function() {
  var add, targetArr;
  targetArr = arguments["0"];
  add = Array.prototype.slice.call(arguments, 1);
  return targetArr.concat(add);
};
