// Generated by CoffeeScript 1.3.3
var trim;

if (String.prototype.trim) {
  trim = function(str) {
    return str.trim();
  };
} else {
  trim = function(str) {
    return str.replace(/^\s+|\s+$/g, "");
  };
}
