// Generated by CoffeeScript 1.3.3

Boolean.prototype.not = function() {
  return !this;
};

TestCase("Boolean Test", {
  "test should flip value of true": function() {
    assertFalse(true.not());
    assertFalse(Boolean.prototype.not.call(true));
  },
  "test should flip value of false": function() {}
});
