// Generated by CoffeeScript 1.3.3
var circle, global;

global = this;

circle = {
  radius: 6,
  diameter: function() {
    return this.radius * 2;
  }
};

TestCase("Circle Test", {
  "test should implicitly bind to object": function() {
    assertEquals(12, circle.diameter());
  },
  "test implicit binding to the global object": function() {
    var myDiameter;
    myDiameter = circle.diameter;
    assertNaN(myDiameter());
    global.radius = 2;
    assertEquals(4, myDiameter());
  },
  "test should call radius on anonymous object": function() {
    assertEquals(10, circle.diameter.call({
      radius: 5
    }));
  }
});
