// Generated by CoffeeScript 1.3.3

TestCase("Sum Test", {
  "test should sum numbers": function() {
    assertEquals(15, sum(1, 2, 3, 4, 5));
    assertEquals(15, sum.apply(null, [1, 2, 3, 4, 5]));
  }
});
