// Generated by CoffeeScript 1.3.3
var obj;

obj = {
  hoge: 100,
  foo: "object",
  bar: true
};

obj = {
  hoge: 100,
  foo: "object",
  bar: true
};

console.log(obj.hoge);

console.log(obj.foo);

console.log(obj.bar);
