// Generated by CoffeeScript 1.3.3
var arr;

arr = [1, 2, 3];

console.log(arr);

arr = [1, 2, 3, 4, 5];

console.log(arr);

arr = [1, 2, 3, 4, 5];

console.log(arr);

arr = [1, 2, 3, 4];

console.log(arr);
