// Generated by CoffeeScript 1.3.3
/*
Basic
*/

var Fuga, Hoge, SubHoge, hoge, subHoge,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hoge = (function() {

  Hoge.prototype.num = 100;

  function Hoge(n) {
    this.num = n;
  }

  Hoge.prototype.printNum = function() {
    return console.log(this.num);
  };

  Hoge.prototype.printSuperNum = function() {
    return console.log("***" + this.num + "***");
  };

  return Hoge;

})();

Hoge.prototype.printSuperNum2 = function() {
  return console.log("===" + this.num + "===");
};

hoge = new Hoge(500);

hoge.printNum();

hoge.printSuperNum();

hoge.printSuperNum2();

/*
Extends class
*/


SubHoge = (function(_super) {

  __extends(SubHoge, _super);

  function SubHoge(n) {
    SubHoge.__super__.constructor.call(this, n);
  }

  SubHoge.prototype.printNum = function() {
    return console.log("---" + this.num + "---");
  };

  return SubHoge;

})(Hoge);

subHoge = new SubHoge(100);

subHoge.printNum();

/*
Check class type
*/


console.log(hoge instanceof SubHoge);

console.log(subHoge instanceof SubHoge);

/*
Static variables
*/


Fuga = (function() {

  function Fuga() {}

  Fuga.num = 128;

  Fuga.func = function() {
    return "I'm static method.";
  };

  return Fuga;

})();

console.log(Fuga.num);

console.log(Fuga.func());
